@istest
public with sharing class MonitoringSummary_API_Wrapper_Test {
    @IsTest
    static void testObject(){
        Object_Test.GetByDateRequestModel();
        Object_Test.GetByDateResponseModel();
        Object_Test.GetByAreaDivisiRequestModel();
        Object_Test.GetByAreaDivisiResponseModel();
        Object_Test.GetByAreaBranchRequestModel();
        Object_Test.GetByAreaBranchResponseModel();
   }
}