public with sharing class SCC_CardAndDigitalLandingLWCController {

   // @AuraEnabled(cacheable=true)
   // public static SCC_CardlinkByPhoneNumberWrapper.Response getCardDetails(String caseId) {
     //   System.debug('Received caseId in getCardDetails: ' + caseId);

        // Call the method to make the callout and retrieve card details
       // SCC_CardlinkByPhoneNumberWrapper wrapper = SCC_CardAndDigitalLandingCallout.makeCallout(caseId);
        
        //if (wrapper != null) {
          //  System.debug('Wrapper response: ' + wrapper);
          //  return wrapper.response;
        //} else {
          //  System.debug('Wrapper response is null.');
            //return null;
       // }
    //}
}