/**
 * @description Wrapper class for Error Log Utility Class
 */
public class SCC_ErrorLogWrapper {
    /**
     * @description apiType
     */
    public String apiType { get; set; }
    /**
     * @description className
     */
    public String className { get; set; }
    /**
     * @description endPoint
     */
    public String endPoint { get; set; }
    /**
     * @description endPointLong
     */
    public String endPointLong { get; set; }
    /**
     * @description errorCause
     */
    public String errorCause { get; set; }
    /**
     * @description errorMessages
     */
    public String errorMessages { get; set; }
    /**
     * @description lineNumber
     */
    public String lineNumber { get; set; }
    /**
     * @description requestHeader
     */
    public String requestHeader { get; set; }
    /**
     * @description requestIP
     */
    public String requestIP { get; set; }
    /**
     * @description requestIPLong
     */
    public String requestIPLong { get; set; }
    /**
     * @description requestBody
     */
    public String requestBody { get; set; }
    /**
     * @description responseHeader
     */
    public String responseHeader { get; set; }
    /**
     * @description responseStatus
     */
    public String responseStatus { get; set; }
    /**
     * @description responseStatusCode
     */
    public Integer responseStatusCode { get; set; }
    /**
     * @description responseBody
     */
    public String responseBody { get; set; }
    /**
     * @description stackTrace
     */
    public String stackTrace { get; set; }
    /**
     * @description errorDatetime
     */
    public DateTime errorDatetime { get; set; }
    /**
     * @description typeName
     */
    public String typeName { get; set; }
    /**
     * @description userRun
     */
    public String userRun { get; set; }
}