name: Deploy to Salesforce Agentforce

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # ambil semua history supaya FROM_COMMIT valid

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y unzip curl openjdk-17-jdk
          npm install --global @salesforce/cli
          echo "y" | sf plugins:install sfdx-git-delta

      - name: Prepare commit range
        id: commits
        run: |
          FROM_COMMIT="${{ github.event.before }}"
          TO_COMMIT="${{ github.sha }}"

          if [ -z "$FROM_COMMIT" ] || [ "$FROM_COMMIT" = "0000000000000000000000000000000000000000" ]; then
            echo "⚠️ No previous commit found, using HEAD^ as FROM_COMMIT"
            FROM_COMMIT=$(git rev-parse HEAD^ || echo "")
          fi

          echo "FROM_COMMIT=$FROM_COMMIT" >> $GITHUB_ENV
          echo "TO_COMMIT=$TO_COMMIT" >> $GITHUB_ENV
          echo "Using commit range: $FROM_COMMIT → $TO_COMMIT"

      - name: Authenticate Salesforce
        run: |
          sf org login jwt \
            --client-id ${{ secrets.AGENTFORCE_CONSUMER_KEY }} \
            --jwt-key-file agentForce_server.key \
            --username ${{ vars.AGENTFORCE_USERNAME }} \
            --instance-url ${{ vars.URL_INSTANCE }} \
            --alias My_Trailhead

      - name: Generate Delta Package (with destructive changes)
        run: |
          if [ -z "$FROM_COMMIT" ]; then
            echo "⚠️ FROM_COMMIT not set, skipping delta package"
            exit 0
          fi

          sfdx sgd:source:delta \
            --from "$FROM_COMMIT" \
            --to "$TO_COMMIT" \
            --output-dir . \
            --ignore-file .gitignore \
            --generate-delta-delete

          echo "✅ Generated package.xml and destructiveChanges.xml (if deletions exist)"
          ls -la package || true
          ls -la destructiveChanges || true

      - name: Validate Deployment (Dry Run)
        run: |
          if [ ! -f "package/package.xml" ] && [ ! -f "destructiveChanges/destructiveChanges.xml" ]; then
            echo "✅ No changes to validate"
            exit 0
          fi

          sf project deploy start \
            --dry-run \
            -x package/package.xml \
            --post-destructive-changes destructiveChanges/destructiveChanges.xml \
            --wait 40 \
            --target-org My_Trailhead \
            --verbose

      - name: Deploy to Salesforce
        if: success()
        run: |
          if [ ! -f "package/package.xml" ] && [ ! -f "destructiveChanges/destructiveChanges.xml" ]; then
            echo "✅ No changes to deploy"
            exit 0
          fi

          echo "⚡ Deploying full delta (includes deletions)"
          sf project deploy start \
            -x package/package.xml \
            --post-destructive-changes destructiveChanges/destructiveChanges.xml \
            --wait 40 \
            --target-org My_Trailhead \
            --verbose
